/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppFormField: typeof import('./src/components/AppFormField.vue')['default']
    AppHeading: typeof import('./src/components/AppHeading.vue')['default']
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    AppToolTip: typeof import('./src/components/AppToolTip.vue')['default']
    Avatar: typeof import('./src/components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    ChevonsLeft: typeof import('./src/components/ui/icon/ChevonsLeft.vue')['default']
    ChevronsRight: typeof import('./src/components/ui/icon/ChevronsRight.vue')['default']
    CircleCheckBig: typeof import('./src/components/ui/icon/CircleCheckBig.vue')['default']
    CircleDashed: typeof import('./src/components/ui/icon/CircleDashed.vue')['default']
    CircleDotDashed: typeof import('./src/components/ui/icon/CircleDotDashed.vue')['default']
    CopyButton: typeof import('./src/components/ui/CopyButton.vue')['default']
    Files: typeof import('./src/components/ui/icon/Files.vue')['default']
    GuestLayout: typeof import('./src/components/layout/GuestLayout.vue')['default']
    Home: typeof import('./src/components/ui/icon/Home.vue')['default']
    Info: typeof import('./src/components/ui/icon/Info.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    LoaderCircle: typeof import('./src/components/ui/icon/LoaderCircle.vue')['default']
    LogOut: typeof import('./src/components/ui/icon/LogOut.vue')['default']
    Menu: typeof import('./src/components/ui/icon/Menu.vue')['default']
    Moon: typeof import('./src/components/ui/icon/Moon.vue')['default']
    PaintBrush: typeof import('./src/components/ui/icon/PaintBrush.vue')['default']
    PencilLine: typeof import('./src/components/ui/icon/PencilLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/ui/icon/Search.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    Settings2: typeof import('./src/components/ui/icon/Settings2.vue')['default']
    StationManager: typeof import('./src/components/StationManager.vue')['default']
    StationManagerTable: typeof import('./src/components/StationManagerTable.vue')['default']
    StationPrices: typeof import('./src/components/StationPrices.vue')['default']
    StationPricesContent: typeof import('./src/components/StationPricesContent.vue')['default']
    SunMedium: typeof import('./src/components/ui/icon/SunMedium.vue')['default']
    Table: typeof import('./src/components/ui/table/Table.vue')['default']
    TableBody: typeof import('./src/components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./src/components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./src/components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./src/components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./src/components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./src/components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./src/components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./src/components/ui/table/TableRow.vue')['default']
    Trash2: typeof import('./src/components/ui/icon/Trash2.vue')['default']
    UserRoundCog: typeof import('./src/components/ui/icon/UserRoundCog.vue')['default']
    X: typeof import('./src/components/ui/icon/X.vue')['default']
  }
}
